### ISSUE TITLE
CMSIS-Atmel not available on ARM Linux - cannot install latest SAMD boards

### ISSUE THREAD

**Issue by oqibidipo** [arduino/ArduinoModule-CMSIS-Atmel#2]
Originally reported on the forum:

http://forum.arduino.cc/index.php?topic=445623.0

> ... IDE 1.8.0 on my Raspberry Pi 2 Model B running the latest Raspbian Jessie

> Under Board Manager I selected "Arduino SAMD Boards (32-bit ARM Cortex-M0+) by Arduino" when I clicked "Install" next to "1.6.11".  I got the following error:
>
> "Tool CMSIS-Atmel is not available for your operating system."

 Add this to `extras/package_index.json.template` (the `"host": "all"` entry does not seem to work).
```
            {
              "host": "arm-linux-gnueabihf",
              "url": "https://github.com/arduino/ArduinoModule-CMSIS-Atmel/releases/download/v%%VERSION%%/%%FILENAME%%",
              "archiveFileName": "%%FILENAME%%",
              "checksum": "SHA-256:%%CHECKSUM%%",
              "size": "%%SIZE%%"
            }
```

**Comment by sandeepmistry** [comment]
@oqibidipo thanks for letting us know.

I've added your suggestion in https://github.com/arduino/ArduinoModule-CMSIS-Atmel/commit/ef0dde6739a8aab7059a876c38d4fdbea0f0443a and also updated http://downloads.arduino.cc/packages/package_index.json.
