### ISSUE TITLE
Won't Build

### ISSUE THREAD

**Issue by fabltd** [arduino/ArduinoModule-CMSIS-Atmel#5]
I get the following error when trying to build:

CMSIS\Device\ATMEL\samd21\include\samd21g18a.h(237,26): error: core_cm0plus.h: No such file or directory

Where is core_cm0Plus.h ?

Thanks

**Comment by sandeepmistry** [comment]
Hi @fabltd,

You can find it in the following repo: https://github.com/ARM-software/CMSIS/tree/8c0e1a91341cde86532b05625f2ad584ce856118 - under `CMSIS/CMSIS/Include/core_cm0plus.h`

**Comment by fabltd** [comment]
Hi

Do i add it here? Device\ATMEL\samd21\include  ?
