### ISSUE TITLE
install into Arduino IDE????

### ISSUE THREAD

**Issue by karu2003** [arduino/ArduinoModule-CMSIS-Atmel#6]
How to install ArduinoModule-CMSIS-Atmel in Arduino IDE.
I want to use SAML21e15b

Th
Andrew.

**Comment by facchinm** [comment]
Hi @karu2003 , this submodule is automatically installed when you install SAMD core so you should be able to use it by including the relevant flags in your `platform.txt` (see https://github.com/arduino/ArduinoCore-samd/blob/master/platform.txt#L67). 
The L21 support is included in any version >= 1.1.0 (which corresponds to SAMD core 1.6.12). Feel free to reopen if needed, thanks!

**Comment by karu2003** [comment]
Thank you,

I installed the SAMD 1.6.15.
I did not find how to add my board.
Please tell me how to add custom Board.

Thank you.
Andrew.

**Comment by facchinm** [comment]
A comprehensive guide on how to add a board can be found here (https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification#boardstxt). If you need additional help, the [forum](https://forum.arduino.cc) is the right place to ask! Thanks!

**Comment by karu2003** [comment]
Thanks!
