### ISSUE TITLE
Add support for SAMD51 series?

### ISSUE THREAD

**Issue by deanm1278** [arduino/ArduinoModule-CMSIS-Atmel#7]
Hello! The team here at Adafruit has a line boards based on the new SAMD51 chip. Would it be ok if I created a pull request adding the SAMD51 CMSIS files? CMSIS files for other devices would not be changed.

**Comment by facchinm** [comment]
Hi @deanm1278 , no problem in updating CMSIS, we only need to take extra care to avoid issues like https://github.com/arduino/ArduinoCore-samd/issues/214 (the DEFINE meaning was changed without changing its name). Feel free to propose a PR if you wish to speedup the process!

**Comment by deanm1278** [comment]
Great! I have proposed this PR https://github.com/arduino/ArduinoModule-CMSIS-Atmel/pull/8
it provides support for samd51 line without interfering with existing CMSIS files

**Comment by cmaglie** [comment]
Further discussion on #8.
